from LanguageEngine import TextClassifier as tc
from ActionBase import FacultyActions as fa
from ActionBase import WebActions as wa
from RecommendationEngine.Code import TeacherRecommender as tr
from ActionBase import DefaultActions as da
import re

classifier = tc.Classifier()

def responceFor(input):
    """
    The central logic of AInstein, it takes the raw input and
    classifies it, finding the slots, class etc

    Parameters
    ----------
    input : str
        The raw input to be understood

    Returns
    -------
    response : str
        The response generated by AInstein
    """
    predictResult = classifier.predict(input)
    questionClass = predictResult["predictions"][0]["intent"].split('.')[0]
    preprocessedQuestion = predictResult["predictions"][0]["originalSentence"]
    if(questionClass == "who"):
        return fa.action(predictResult)
    
    elif(questionClass == "what"):
        noOfWordsRegex = re.compile(r'In \d+ Words')
        noOfWordsRegexSearch = noOfWordsRegex.search(preprocessedQuestion)
        if noOfWordsRegexSearch is None:
            return wa.scrapeDescription(fa.extractName(preprocessedQuestion))
        else:
            return wa.scrapeDescription(fa.extractName(preprocessedQuestion), int(noOfWordsRegexSearch.group().split(' ')[1]))
    
    elif questionClass == "recommend":
        interests = fa.extractName(preprocessedQuestion)
        return tr.recommendTeacher(interests)
    
    else:
        response = da.defaultAnswer(predictResult['predictions'][0]['intent'])
        return response

    return "Oops, I can't understand"
